#!/usr/bin/env python3

# Portal Constants

# MetaWorkflow names are used to get the latest version.
# We assume that they don't change!
MWF_NAME_ILLUMINA = "Illumina_alignment_GRCh38"
MWF_NAME_ONT = "ONT_alignment_GRCh38"
MWF_NAME_PACBIO = "PacBio_alignment_GRCh38"
MWF_NAME_RNASEQ = "RNA-seq_bulk_short_reads_GRCh38"
MWF_NAME_KINNEX = "RNA-seq_kinnex_long_reads_GRCh38"
MWF_NAME_HIC = "Hi-C_alignment_GRCh38"
MWF_NAME_FASTQC = "Illumina_FASTQ_quality_metrics"
MWF_NAME_FASTQ_LONG_READ = "long_reads_FASTQ_quality_metrics"
MWF_NAME_FASTQ_SHORT_READ = "short_reads_FASTQ_quality_metrics"
MWF_NAME_CRAM_TO_FASTQ_PAIRED_END = "cram_to_fastq_paired-end"
MWF_NAME_BAM_TO_FASTQ_PAIRED_END = "bam_to_fastq_paired-end"
MWF_NAME_BAM_TO_CRAM = "bam_to_cram"
MWF_NAME_BAMQC_SHORT_READ = "paired-end_short_reads_BAM_quality_metrics_GRCh38"
MWF_NAME_ULTRA_LONG_BAMQC = "ultra-long_reads_BAM_quality_metrics_GRCh38"
MWF_NAME_LONG_READ_BAMQC = "long_reads_BAM_quality_metrics_GRCh38"
MWF_SAMPLE_IDENTITY_CHECK = "sample_identity_check"
# Variant callering
MWF_NAME_TNHAPLOTYPER = "paired-end_short_reads_variant_calling_TNhaplotyper2_distributed_TNfilter_GRCh38"
MWF_NAME_LONGCALLD = "PacBio_variant_calling_longcallD_GRCh38"
MWF_NAME_LONGCALLD_SINGLE_FILE = "PacBio_variant_calling_longcallD_single_file_GRCh38"
MWF_NAME_STRELKA2 = "paired-end_short_reads_variant_calling_Strelka2_distributed_GRCh38"
MWF_NAME_RUFUS = "paired-end_short_reads_variant_calling_RUFUS_distributed_GRCh38"
MWF_NAME_DNASCOPEHYBRID = "paired-end_short_plus_PacBio_variant_calling_DNAscopeHybrid_GRCh38"
MWF_NAME_SNIFFLES = "PacBio_ONT_variant_calling_Sniffles_GRCh38"
MWF_NAME_SEVERUS = "PacBio_ONT_variant_calling_Severus_GRCh38"
MWF_NAME_DELLY = "PacBio_ONT_variant_calling_Delly_GRCh38"
MWF_NAME_SNV_FILTERING_LONGCALLD = "SNV_filtering_longcallD_GRCh38"
MWF_NAME_SNV_FILTERING = "SNV_filtering_GRCh38"

HMS_DAC_UUID = "9626d82e-8110-4213-ac75-0a50adf890ff"

# Input argument names
INPUT_FILES_R1_FASTQ_GZ = "input_files_r1_fastq_gz"
INPUT_FILES_R2_FASTQ_GZ = "input_files_r2_fastq_gz"
INPUT_FILES_BAM = "input_files_bam"
INPUT_FILES = "input_files"
INPUT_FILES_FASTQ_GZ = "input_files_fastq_gz"
INPUT_FILES_CRAM = "input_files_cram"
INPUT_FILE_CRAM = "input_file_cram"
ADDITIONAL_INPUT_FILES_CRAM = "additional_input_files_cram"
GENOME_REFERENCE_FASTA = "genome_reference_fasta"
SAMPLE_NAME = "sample_name"
SAMPLE_NAMES = "sample_names"
LENGTH_REQUIRED = "length_required"
LIBRARY_ID = "library_id"
GENOME_REFERENCE_STAR = "genome_reference_star"
STRANDEDNESS = "strandedness"

# Schema fields
COMMON_FIELDS = "common_fields"
UUID = "uuid"
COMPLETED = "completed"
DESCRIPTION = "description"
TAGS = "tags"
SUBMISSION_CENTERS = "submission_centers"
SEQUENCING_CENTER = "sequencing_center"
CONSORTIA = "consortia"
FILE_SETS = "file_sets"
ANALYSIS_RUNS = "analysis_runs"
META_WORKFLOW_RUN = "MetaWorkflowRun"
ANALYSIS_RUN = "AnalysisRun"
ACCESSION = "accession"
DISPLAY_TITLE = "display_title"
ALIASES = "aliases"
UPLOADED = "uploaded"
RELEASED = "released"
OPEN = "open"
OPEN_NETWORK = "open-network"
OPEN_EARLY = "open-early"
PROTECTED = "protected"
PROTECTED_NETWORK = "protected-network"
PROTECTED_EARLY = "protected-early"
DELETED = "deleted"
STATUS = "status"
FIRST_STRANDED = "First Stranded"
SECOND_STRANDED = "Second Stranded"
FAILED_JOBS = "failed_jobs"
SOMATIC_SNV_CALLING = "Somatic SNV calling"
SOMATIC_SNV_CALLING_CORE_SPECIFIC = "Somatic SNV calling (core specific)"
SOMATIC_SV_CALLING = "Somatic SV calling"
GERMLINE_SNV_CALLING = "Germline SNV calling"

# Assays
WGS = "WGS"
RNASEQ = "RNA-seq"